### ISSUE TITLE
bug(ci): the `lint` job runs zero ESLint tasks — `turbo run lint --filter=!@open-mercato/app` matches no scripts

### ISSUE THREAD

**Issue by wojciechszyjka** [open-mercato/open-mercato#4472]
## Summary

The CI `lint` job passes on every PR without running ESLint on a single file. `.github/workflows/ci.yml` invokes

```yaml
- name: Lint
  run: yarn turbo run lint --filter=!@open-mercato/app
```

but **`@open-mercato/app` is the only workspace in the monorepo that defines a `lint` script**. Excluding it leaves turbo with nothing to execute, so the job is a no-op that always reports success.

The repo therefore has **no enforced ESLint coverage in CI today**.

## Evidence (on `develop`, af142c574)

Every workspace `package.json` with a `lint` script:

| file | package | script |
|---|---|---|
| `apps/mercato/package.json` | `@open-mercato/app` | `eslint .` |
| `package.json` (root) | `open-mercato` | `turbo run lint` (passthrough, not a workspace task) |

No other package defines one. Turbo dry-run of the exact CI command:

```
$ yarn turbo run lint --filter='!@open-mercato/app' --dry=text
Tasks to Run
  Command = <NONEXISTENT>   × 23
```

23 packages in scope, 23 non-existent commands, exit 0.

The filter was introduced in #1509 (`perf(ci): parallel job graph, sharded integration tests, Turbo cache`) — presumably to skip the slow Next app lint — but the side effect is that nothing is linted at all.

## Why it matters (concrete case)

On #4458 (`build(deps-dev): port ESLint 10.7.0 to develop`) every CI check is green while local `yarn lint` crashes deterministically with ESLint 10:

- `eslint-plugin-react@7.37.5` → `TypeError: contextOrFilename.getFilename is not a function`
- `eslint-config-next/parser@16.2.11` → `scopeManager.addGlobals is not a function`

CI did not — and structurally cannot — catch either. On that PR the `blocked` label is doing 100% of the gatekeeping. Details: https://github.com/open-mercato/open-mercato/pull/4458#issuecomment-5068798712

## Proposed fix

The lint job should actually lint `apps/mercato`, which is where all the ESLint config and virtually all lintable app code lives. Options, cheapest first:

1. **Drop the exclusion** — `yarn turbo run lint` (or `yarn workspace @open-mercato/app lint`). Needs a check of how long `eslint .` takes on `apps/mercato` in CI and whether the current 12 warnings should stay non-blocking (`--max-warnings`).
2. **Keep the exclusion but add real lint scripts** to the packages that should be linted, plus a `lint` task entry in `turbo.json` with proper `inputs` for caching.
3. **Fail loudly on an empty task graph** — a guard that errors when `turbo run lint` resolves zero commands, so a future filter/script change cannot silently disable the gate again.

(1) + (3) restores the gate with the smallest diff; (2) is the larger cleanup.

## Notes

- Independent of #4458 — this is broken on `develop` today, not caused by that PR.
- Related but distinct: #4328 (scaffolded create-app ships broken `lint`/`test` scripts).
- Suggested labels (I cannot set them): `bug`, `priority-medium`, `risk-low`.

*Verified on `develop` @ af142c574 with Node 24.14.1.*

**Comment by wojciechszyjka** [comment]
Fixed on `develop` by #4501 (merge commit `c8a615e53`), which carried forward the implementation from the closed #4496.

The lint job now runs:

```yaml
- name: Guard against an empty lint task graph
  run: yarn lint:check-graph

- name: Lint
  run: yarn lint
```

That covers both option (1) and option (3) from the report: the filter that excluded `@open-mercato/app` — the only workspace with a `lint` script — is gone, and `scripts/check-turbo-task-graph.mjs` now fails the job when `turbo run lint` resolves to zero executable commands, so a future filter change or script rename cannot silently disable the gate again. Regression coverage lives in `scripts/__tests__/lint-task-graph.test.mjs`.

Verified against `develop` after the merge: `yarn lint` resolves one real command (`@open-mercato/app#lint => eslint .`) and completes in ~6 s with 0 errors / 12 warnings, so warnings stay non-blocking as discussed. Option (2) — real `lint` scripts for the remaining 23 packages — was left out of scope.

This issue stayed open only because the merge landed on `develop` rather than the repository's default branch, so GitHub did not auto-close it. Closing manually.
