### PR TITLE
feat(security): declare ACL feature dependencies (#2172)

### LINKED ISSUE #2172: feat(security): declare ACL feature dependencies
## Context

This issue is a per-module follow-up to PR #2141 (`feat(auth): ACL dependency bundles`), which introduced an optional `dependsOn?: string[]` field on every feature descriptor and a warning UX in `AclEditor` that fires whenever a granted feature's declared dependencies are missing.

The PR shipped the **infrastructure** (resolver, API forwarding, UI panel) and used `customers` as the reference module. Every other module still needs its `acl.ts` updated.

## What to do

Pick the proposed dependency table for this module from the spec:

- Spec: [`.ai/specs/2026-05-27-acl-dependency-bundles.md`](https://github.com/open-mercato/open-mercato/blob/develop/.ai/specs/2026-05-27-acl-dependency-bundles.md)
- This module's section is linked below in **Spec section**.

Update the module's `acl.ts` to add `dependsOn: [...]` to each feature per the table.

**MUST also:**

1. Refine the proposed table if it's wrong for the module (the spec calls it a "proposed default" — module owners know the page wiring better).
2. Add new view-grained features when the spec table marks a dep with `*` (e.g. the sales follow-up MUST introduce `sales.channels.view` and `sales.settings.view`).
3. Update `setup.ts` `defaultRoleFeatures` for any new view-grained features.
4. Run `yarn mercato auth sync-role-acls` after deploy so existing tenants pick up new view features.
5. Add unit tests asserting `acl.ts` declarations resolve cleanly against the catalog (no `unknownReferences` for this module's own features).
6. Open a PR titled `feat(<module>): declare ACL feature dependencies` and reference this issue.

## Reference implementation

The customers module landed in PR #2141 as the reference:

- `packages/core/src/modules/customers/acl.ts` — flat list with `dependsOn` arrays.
- `.ai/specs/2026-05-27-acl-dependency-bundles.md` §6.1 — the table that was enacted.

## Why warnings only (not blocking saves)

This is intentional per spec §4.6 — server-side enforcement is filed as a separate follow-up so that bad declarations can't break production saves. Today the operator gets a warning and can still save.

## Acceptance

- [ ] `acl.ts` declares `dependsOn` for every feature where a real dependency exists.
- [ ] `setup.ts` `defaultRoleFeatures` updated for any new view-grained features.
- [ ] No `unknownReferences` reported for this module's own ids when running `resolveAclDependencyDiagnostics` against the module catalog.
- [ ] Targeted yarn typecheck + scoped jest tests pass.
- [ ] PR references this issue and the umbrella spec.

## Spec section

[spec §6.33](https://github.com/open-mercato/open-mercato/blob/develop/.ai/specs/2026-05-27-acl-dependency-bundles.md#633-enterprisesecurity)

Enterprise overlay module — `packages/enterprise/src/modules/security/`.

### PR DESCRIPTION
**Pull request by pkarw**
Fixes #2172

## Problem
The enterprise `security` module's `acl.ts` had not yet been updated for the ACL dependency bundles shipped in PR #2141. Granting a manage/action feature without its prerequisite read feature produced no operator warning.

## Root Cause
`security/acl.ts` declared a flat feature list with no `dependsOn` arrays, so `resolveAclDependencyDiagnostics` reported no missing dependencies for the module.

## What Changed
- `packages/enterprise/src/modules/security/acl.ts` — declared `dependsOn` per spec [§6.33](https://github.com/open-mercato/open-mercato/blob/develop/.ai/specs/2026-05-27-acl-dependency-bundles.md#633-enterprisesecurity):
  - `security.profile.password`, `security.profile.manage`, `security.mfa.manage` → `security.profile.view`
  - `security.admin.manage` → `security.profile.view`, `auth.users.list`
  - `security.sudo.manage` → `security.sudo.view`
- No new view-grained features (the §6.33 table has no `*` deps), so `setup.ts` `defaultRoleFeatures` is unchanged — `admin` keeps `security.*` and the `employee` allowlist already grants `security.profile.view`. The cross-module `auth.users.list` dep is already granted to admin via the auth module. No `sync-role-acls` run is required.

## Tests
- New `packages/enterprise/src/modules/security/__tests__/acl-dependencies.test.ts` (5 tests):
  - every security `dependsOn` resolves cleanly against the security+auth catalog (no `unknownReferences`)
  - granting `security.admin.manage` alone surfaces its missing read deps (`auth.users.list`, `security.profile.view`)
  - manage/action features depend on their view feature; view features declare no deps
  - default role features cover the security view dependencies
- Verified red before the fix (2/5 fail), green after (5/5 pass).
- Pre-existing, unrelated env failures in the broader security suite (MFA/sudo command/route/component tests fail on `Cannot find module '@open-mercato/cache'` / React env skew) and `typecheck` (`#generated` shim + an unrelated `record_locks` page) are not touched by this change.

## Backward Compatibility
- No contract surface changes. `dependsOn` is the optional, additive field introduced by #2141; no feature IDs were added, removed, or renamed.

### CODE REVIEW

**Comment by pkarw** [comment]
Label set to `review` because the fix PR is ready for code review.

**Comment by pkarw** [comment]
Label set to `skip-qa` because this is a low-risk, non-customer-facing ACL declaration change (additive `dependsOn` metadata + unit tests, no runtime/UI behavior change) that does not need manual QA.

**Review by pkarw — COMMENTED** [review]
🤖 Comment-only review (`auto-review-pr`) — author is the reviewer, so no formal verdict can be submitted.

**`security` ACL dependency declarations — looks good.** Adds `dependsOn` to `security/acl.ts` plus a self-validating dependency test (`resolveAclDependencyDiagnostics`): asserts dependsOn targets are registered in the catalog, no missing deps when all features are granted, missing-dep surfacing for partial grants, and every internal target stays within the module's feature set. Additive (new optional ACL metadata), part of the #2141 ACL-dependency-bundles feature, well-scoped. ✅ No blocking findings. Recommend a quick check that `setup.ts` `defaultRoleFeatures` still satisfy the new deps for seeded roles.
