### PR TITLE
perf(communication_channels): sanitize channel HTML server-side, off the client render path (#3182)

### LINKED ISSUE #3182: perf(communication_channels): stop sanitizing channel HTML in the client render path
## Problem

The channel payload renderer is a client component, but it imports and runs `sanitizeChannelHtml()` during render. That helper imports `sanitize-html`, so the email payload widget can pull the sanitizer/htmlparser dependency chain into the browser bundle and pay sanitization cost on the client render path.

## Evidence

- `packages/core/src/modules/communication_channels/widgets/injection/channel-payload-renderer/widget.client.tsx:6` imports `sanitizeChannelHtml`.
- `packages/core/src/modules/communication_channels/widgets/injection/channel-payload-renderer/widget.client.tsx:30-40` sanitizes `channelPayload.html` inside the client component before `dangerouslySetInnerHTML`.
- `packages/core/src/modules/communication_channels/lib/sanitize-channel-html.ts:1` imports `sanitize-html`.
- `packages/core/package.json` declares `sanitize-html`, so this is a real module dependency, not a local stub.

## Expected fix

Keep the HTML safety guarantee, but move sanitization off the client render path. Prefer sanitizing in the server/API/enricher path and returning a clearly named sanitized HTML field to the widget, or introduce a server-only wrapper so the client component does not import `sanitize-html` directly.

Add focused coverage that proves the widget receives sanitized content and that unsafe HTML remains stripped before rendering.

### PR DESCRIPTION
**Pull request by haxiorz**
## Summary

The channel-payload renderer is a client component (`'use client'`) that imported `sanitizeChannelHtml()` and ran it during render. That helper imports `sanitize-html`, so the email payload widget pulled the sanitizer/htmlparser dependency chain into the browser bundle and paid sanitization cost on the client render path. This moves sanitization to the server-side response enricher and has the client widget render a clearly-named, pre-sanitized field — keeping the HTML safety guarantee while taking `sanitize-html` off the client.

## Changes

- `data/enrichers.ts`: the server-only `communication_channels.message-channel-payload` enricher now sanitizes `email/*` HTML via `sanitizeChannelHtml` and exposes it as a new `_channelPayload.sanitizedHtml` field (`string | null`). Raw `channelPayload` is preserved (additive — provider widget overrides keep their data contract).
- `widget.client.tsx`: removed the `sanitize-channel-html` import; the email branch renders `_channelPayload.sanitizedHtml` via `dangerouslySetInnerHTML`. No sanitizer in the client bundle, no client-side sanitization cost.
- `widget.ts`: updated the metadata comment to reflect server-side sanitization.
- Added focused tests proving (a) the enricher sanitizes server-side and strips unsafe HTML, and (b) the client component no longer imports the sanitizer and renders the pre-sanitized field.

## Specification

**Does a spec exist for this feature/module?**
- [ ] Yes
- [ ] No (created a new spec)
- [x] N/A (minor change, no spec needed)

**Spec file path:**
N/A — performance refactor of an existing widget; behavior (sanitized email rendering, per SPEC-045d §4.6) is unchanged.

## Testing

List the tests or commands you ran to validate the change.

- `yarn jest src/modules/communication_channels/data/__tests__/channel-payload-enricher.test.ts src/modules/communication_channels/widgets/injection/channel-payload-renderer/__tests__/widget.client.test.tsx` (in `packages/core`) — 6 tests, red before the fix → green after.
- `yarn jest src/modules/communication_channels` (in `packages/core`) — 544/544 pass (56 suites).
- `turbo run typecheck --filter=@open-mercato/core` — pass.
- `yarn workspace @open-mercato/core build` — pass.
- `TURBO_FORCE=1 yarn build:app` — pass (exit 0).
- `yarn i18n:check-sync` — all locales in sync.

## Checklist

- [x] This pull request targets `develop`.
- [x] I have read and accept the Open Mercato Contributor License Agreement (see `docs/cla.md`).
- [x] I updated documentation, locales, or generators if the change requires it. (Updated the widget metadata comment; no locale/generator changes — reuses the existing `communication_channels.channelPayload.email.aria` key.)
- [x] I added or adjusted tests that cover the change.
- [x] I added or updated integration tests in `.ai/qa/tests/` (or documented why integration coverage is not required). — N/A: internal refactor of a server enricher + client widget with no new API/route surface; covered by focused unit tests (enricher sanitization + client import-graph guard). No user-facing flow changed.
- [ ] I created or updated the spec in `.ai/specs/` with a changelog entry (if applicable). — N/A, no spec change.
- [x] Priority set: this PR carries exactly one `priority-*` label. (`priority-medium`, inherited from the issue.)
- [x] Risk set: this PR carries exactly one `risk-*` label describing its blast radius. (`risk-medium`, inherited from the issue — single-module change.)
- [x] QA routing set: `skip-qa` for low-risk non-customer-facing changes, otherwise `needs-qa`. — `skip-qa`: refactor with identical rendered output, fully unit-covered, no customer-facing behavior change.

### Design System Compliance
- [x] No hardcoded status colors — N/A, no UI styling changed.
- [x] No arbitrary text sizes — N/A, no UI styling changed.
- [x] Empty state handled for list/data pages — N/A, not a list/data page.
- [x] Loading state handled for async pages — N/A, synchronous widget.
- [x] `aria-label` on all icon-only buttons — N/A, no buttons (existing `aria-label` on the email section preserved).
- [x] Uses existing DS components — N/A, no component changes; existing markup preserved.

## Linked issues

Fixes #3182

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by haxiorz** [comment]
Labels: `review` (ready for review), `refactor`+`performance` (perf refactor — moves `sanitize-html` off the client render path), `priority-medium` + `risk-medium` (inherited from #3182; single-module change). `skip-qa`: rendered output is identical (same allowlist sanitizer, now computed server-side), no customer-facing behavior change, and the render path is unit-covered + `build:app` passes — so no manual QA gate is required.

**Comment by pkarw** [comment]
🤖 `auto-review-pr` started by @pkarw at 2026-06-21T03:20:08Z. Other auto-skills will skip this PR until the lock is released.

**Review by pkarw — APPROVED** [review]
## Code Review: perf(communication_channels): sanitize channel HTML server-side

**Verdict: Approved**

This is a clean, well-scoped performance refactor that moves email-HTML sanitization off the client render path while preserving the XSS-safety guarantee.

### What was reviewed
- `data/enrichers.ts` — server-only enricher now sanitizes `email/*` HTML via `sanitizeChannelHtml` and exposes it as the additive `_channelPayload.sanitizedHtml` (`string | null`).
- `widget.client.tsx` — dropped the `sanitize-channel-html` import; the email branch renders the pre-sanitized `sanitizedHtml`. No `sanitize-html` in the client bundle.
- `widget.ts` — metadata comment updated.
- Two new focused test files (6 tests).

### Findings
- **Critical: 0** — No frozen contract surface touched. Event IDs, widget spot IDs, DB schema, and import paths are unchanged. The new `sanitizedHtml` field is purely **additive**; raw `channelPayload` is preserved, so provider-package UMES overrides keep their data contract.
- **High: 0** — `findWithDecryption` is retained (not downgraded to raw `em.find`). Tenant isolation is intact: the enricher query scopes by both `tenantId` and `organizationId`. Behavior change ships with tests.
- **Medium: 0** — No hardcoded user-facing strings (the existing `communication_channels.channelPayload.email.aria` i18n key is reused), no `any`, no schema/migration change.
- **Low: 0**

### Security note (positive)
Sanitization now runs server-side and the client renders `_channelPayload.sanitizedHtml` via `dangerouslySetInnerHTML`. The XSS guarantee per SPEC-045d §4.6 is preserved; the client-bundle attack surface and render-path cost both shrink. The `sanitizedHtml` field is correctly null for non-`email/*` payloads and for email payloads without an html body.

### Verification performed
- Focused unit tests run in the isolated worktree: **6/6 pass** (`channel-payload-enricher.test.ts` + `widget.client.test.tsx`).
- Confirmed no other package or the official-modules submodule consumes `_channelPayload`/`channel-payload-renderer` in a way the additive field would break.
- CI on the PR is green (`test`, `lint`, `audit`, `ephemeral-integration`, `cla` all pass).

Approving and routing to `merge-queue` (`skip-qa` present, no QA gate required).

**Comment by pkarw** [comment]
Label set to `merge-queue` because code review passed and `skip-qa` is present (no manual QA gate required).

**Comment by pkarw** [comment]
🤖 `auto-review-pr` completed: APPROVED. Routed to `merge-queue` (skip-qa). 0 critical / 0 high / 0 medium / 0 low findings. Lock released.

**Comment by pkarw** [comment]
🤖 `auto-review-pr` started by @pkarw at 2026-06-22T20:54:35Z. Resolving merge conflicts against `develop` (autofix). Other auto-skills will skip this PR until the lock is released.

**Comment by pkarw** [comment]
## Re-review: perf(communication_channels): sanitize channel HTML server-side

**Verdict: Approved (carried forward) — conflicts resolved, re-validated.**

The PR was `CONFLICTING/DIRTY` against `develop`. I merged the latest `develop` (`630752a1c`) into the branch and reconciled a genuine semantic conflict in `packages/core/src/modules/communication_channels/data/enrichers.ts`.

### Why it conflicted
- `develop` landed #3183, which **batched** the three separate enrichers (`_channel` / `_channelPayload` / `_channelContact`) into one `messageChannelEnricher` to remove the duplicated `MessageChannelLink` lookups.
- This PR added server-side email-HTML sanitization to the (previously separate) payload enricher.

### How I resolved it
- Moved the PR's `sanitizeEmailPayloadHtml` helper and the additive `_channelPayload.sanitizedHtml` field onto the **batched** `messageChannelEnricher` (kept develop's single-pass batching).
- Added `sanitizedHtml: string | null` to the canonical `ChannelPayloadEnrichment` type (dropped the PR's now-duplicate type definition).
- Updated `channel-payload-enricher.test.ts` to target the batched enricher id (`communication_channels.message-channel`); its fixtures carry no `externalConversationId`, so the batched enricher's extra lookups stay short-circuited and the test still exercises only the sanitization path.
- The XSS guarantee is preserved: sanitization runs server-side; the client renders `_channelPayload.sanitizedHtml` and never imports `sanitize-html`. Raw `channelPayload` is left intact for provider widget overrides.

The merge was pushed as a single clean merge commit to the fork branch (`maintainerCanModify: true`), preserving @haxiorz's authorship.

### Validation (in an isolated worktree)
- Focused tests: **16/16 pass** (`channel-payload-enricher.test.ts` + develop's `enrichers.test.ts` incl. the #3183 no-N+1 guard + `widget.client.test.tsx`).
- `@open-mercato/core` esbuild build: **passes** (3393 entry points).
- Type check of the changed scope: **clean** (the only `tsc` errors in this worktree are pre-existing `#generated` module-resolution noise; none in `communication_channels`).

No new findings. Head is now `MERGEABLE`; keeping `merge-queue` (`skip-qa`, no QA gate).

**Comment by pkarw** [comment]
🤖 `auto-review-pr` completed: **APPROVED** (re-review). 1 autofix iteration: merged `develop` (630752a1c), reconciled the `enrichers.ts` semantic conflict against #3183's batched enricher, updated the affected test, and pushed a single clean merge commit (`9109ec787`) to the fork branch. Validation green (16/16 focused tests, core esbuild build OK, changed-scope typecheck clean). PR is now `MERGEABLE` and stays in `merge-queue` (`skip-qa`). Lock released.

**Comment by pkarw** [comment]
🤖 `auto-review-pr` (autofix) re-entry by @pkarw at 2026-06-24T09:08:23Z. The `test` check is red on a single unrelated suite (`feature_toggles/override-list-openapi-schema`, `em.count is not a function`) that is already fixed on `develop` (commit a45eec623). Merging the latest `develop` into the fork branch to bring the fix in and turn CI green.

**Review by patzick — APPROVED** [review]
