### PR TITLE
fix(ci): restore ESLint coverage in the lint job (#4472)

### LINKED ISSUE #4472: bug(ci): the `lint` job runs zero ESLint tasks — `turbo run lint --filter=!@open-mercato/app` matches no scripts
## Summary

The CI `lint` job passes on every PR without running ESLint on a single file. `.github/workflows/ci.yml` invokes

```yaml
- name: Lint
  run: yarn turbo run lint --filter=!@open-mercato/app
```

but **`@open-mercato/app` is the only workspace in the monorepo that defines a `lint` script**. Excluding it leaves turbo with nothing to execute, so the job is a no-op that always reports success.

The repo therefore has **no enforced ESLint coverage in CI today**.

## Evidence (on `develop`, af142c574)

Every workspace `package.json` with a `lint` script:

| file | package | script |
|---|---|---|
| `apps/mercato/package.json` | `@open-mercato/app` | `eslint .` |
| `package.json` (root) | `open-mercato` | `turbo run lint` (passthrough, not a workspace task) |

No other package defines one. Turbo dry-run of the exact CI command:

```
$ yarn turbo run lint --filter='!@open-mercato/app' --dry=text
Tasks to Run
  Command = <NONEXISTENT>   × 23
```

23 packages in scope, 23 non-existent commands, exit 0.

The filter was introduced in #1509 (`perf(ci): parallel job graph, sharded integration tests, Turbo cache`) — presumably to skip the slow Next app lint — but the side effect is that nothing is linted at all.

## Why it matters (concrete case)

On #4458 (`build(deps-dev): port ESLint 10.7.0 to develop`) every CI check is green while local `yarn lint` crashes deterministically with ESLint 10:

- `eslint-plugin-react@7.37.5` → `TypeError: contextOrFilename.getFilename is not a function`
- `eslint-config-next/parser@16.2.11` → `scopeManager.addGlobals is not a function`

CI did not — and structurally cannot — catch either. On that PR the `blocked` label is doing 100% of the gatekeeping. Details: https://github.com/open-mercato/open-mercato/pull/4458#issuecomment-5068798712

## Proposed fix

The lint job should actually lint `apps/mercato`, which is where all the ESLint config and virtually all lintable app code lives. Options, cheapest first:

1. **Drop the exclusion** — `yarn turbo run lint` (or `yarn workspace @open-mercato/app lint`). Needs a check of how long `eslint .` takes on `apps/mercato` in CI and whether the current 12 warnings should stay non-blocking (`--max-warnings`).
2. **Keep the exclusion but add real lint scripts** to the packages that should be linted, plus a `lint` task entry in `turbo.json` with proper `inputs` for caching.
3. **Fail loudly on an empty task graph** — a guard that errors when `turbo run lint` resolves zero commands, so a future filter/script change cannot silently disable the gate again.

(1) + (3) restores the gate with the smallest diff; (2) is the larger cleanup.

## Notes

- Independent of #4458 — this is broken on `develop` today, not caused by that PR.
- Related but distinct: #4328 (scaffolded create-app ships broken `lint`/`test` scripts).
- Suggested labels (I cannot set them): `bug`, `priority-medium`, `risk-low`.

*Verified on `develop` @ af142c574 with Node 24.14.1.*

### PR DESCRIPTION
**Pull request by wojciechszyjka**
## Summary

`.github/workflows/ci.yml` ran `yarn turbo run lint --filter=!@open-mercato/app`, but `@open-mercato/app` is the **only** workspace that defines a `lint` script. Excluding it left turbo with 23 `<NONEXISTENT>` commands, so the job exited 0 without linting a single file — the repo had no enforced ESLint coverage in CI.

This restores the gate (option 1 + 3 from the issue) and makes the failure mode impossible to reintroduce silently.

Fixes #4472

## Changes

- `.github/workflows/ci.yml`: the `Lint` step now runs `yarn lint` (`turbo run lint`, no filter), and the stale comment claiming the app "requires an ESLint config that is not yet present in the repo" is corrected — `eslint.config.mjs` has existed at the repo root for a while.
- New step `Guard against an empty lint task graph` runs `yarn lint:check-graph` before linting.
- `scripts/check-turbo-task-graph.mjs` (new): reads `turbo run <task> --dry=json` and exits 1 when the task resolves to zero executable commands, so a future filter change or script rename cannot turn the gate back into a no-op. Reusable for other turbo-backed gates (`node scripts/check-turbo-task-graph.mjs test --filter=./packages/*`).
- `package.json`: new `lint:check-graph` script.
- `scripts/__tests__/lint-task-graph.test.mjs` (new): unit tests for the guard's parsing/filtering plus repo invariants — at least one workspace defines `lint`, the root `lint` script fans out via turbo, and the CI lint job does not filter every lint script away.

Warnings stay non-blocking (no `--max-warnings`): `apps/mercato` currently reports 0 errors / 12 warnings, and pinning that count would be brittle. Adding real `lint` scripts to `packages/*` (option 2 in the issue) is deliberately out of scope — a full-repo `eslint .` runs for well over 10 minutes on this tree and would need its own triage pass.

## Specification

**Does a spec exist for this feature/module?**
- [ ] Yes
- [ ] No (created a new spec)
- [x] N/A (minor change, no spec needed)

**Spec file path:** N/A

## Testing

Runner: local (no `app` container running).

- `yarn lint` → `@open-mercato/app#lint` runs `eslint .`, 1 successful task, **0 errors / 12 warnings**, ~7 s cold. Verified against this branch's tree (rebased on `develop`).
- `yarn lint:check-graph` → `` `turbo run lint` runs 1 command(s): @open-mercato/app#lint `` (exit 0).
- Guard reproduces the bug: `node scripts/check-turbo-task-graph.mjs lint '--filter=!@open-mercato/app'` → `resolves to zero executable commands` (exit 1).
- `yarn test:scripts` → 330 tests, 330 pass, 0 fail.

## Checklist

- [x] This pull request targets `develop`.
- [x] I have read and accept the Open Mercato Contributor License Agreement (see `docs/cla.md`).
- [x] I updated documentation, locales, or generators if the change requires it. (CI comment corrected; no docs reference the old command.)
- [x] I added or adjusted tests that cover the change.
- [x] I added or updated integration tests in `.ai/qa/tests/` (or documented why integration coverage is not required) — CI-only change with no runtime/API/UI surface; covered by `scripts/__tests__/lint-task-graph.test.mjs`.
- [ ] I created or updated the spec in `.ai/specs/` with a changelog entry (if applicable).
- [ ] Priority set: this PR carries exactly one `priority-*` label.
- [ ] Risk set: this PR carries exactly one `risk-*` label describing its blast radius.
- [ ] QA routing set.

Suggested labels (my account cannot set them on this repo): `bug`, `review`, `skip-qa`, `priority-medium`, `risk-low` — CI-only, no customer-facing surface.

### Design System Compliance

N/A — no UI code touched.

## Linked issues

Fixes #4472

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by wojciechszyjka** [comment]
🤖 CI diagnosis — the red `audit` check is not caused by this diff.

`audit` fails on [GHSA-r28c-9q8g-f849](https://github.com/advisories/GHSA-r28c-9q8g-f849) (high): `postcss` `8.5.15`, vulnerable range `<= 8.5.17`, pulled in by `next@16.2.11`. Failing step in [run 30122095136](https://github.com/open-mercato/open-mercato/actions/runs/30122095136/job/89577616794):

```
└─ postcss
   ├─ ID: 1124288
   ├─ Severity: high
   ├─ Vulnerable Versions: <=8.5.17
   └─ Dependents
      └─ next@npm:16.2.11 [b3a03]
```

The root cause is repo-wide, not branch-local: root `package.json` pins `resolutions["postcss"] = "8.5.15"`, so the tree cannot move onto the patched `8.5.18+` on its own. It looks intermittent only because the `audit` job caches its result under a manifest hash (`ci.yml:293-300`) — PRs that hit the cache report a stale green.

Filed as #4499 with the fix steps. This PR needs no change for it; it will go green once #4499 lands (or on a run served from cache).

**Comment by pkarw** [comment]
🤖 `om-auto-review-pr` started by @pkarw at 2026-07-25T04:35:58Z. Other auto-skills will skip this PR until the lock is released.

**Review by pkarw — CHANGES_REQUESTED** [review]
# Code Review: fix(ci): restore ESLint coverage in the lint job (#4472)

## Summary
The lint restoration itself is well-scoped and its dedicated `lint` check passed. The current PR head cannot advance yet because GitHub reports a failing `audit` check; branch protection is not readable, so the review workflow treats every reported PR check as required. The audit failure is the repository-wide postcss advisory already fixed on `develop` by #4500, so the branch needs to be carried forward onto the updated base and rechecked.

## Verdict
request changes — the current head has a failing required CI signal (`audit`).

## Validation Gate

Validation source: GitHub checks
Runner: GitHub Actions

| Check | Status | Notes |
|---|---|---|
| prepare | PASS | GitHub check |
| audit-scope | PASS | GitHub check |
| lint | PASS | Guard and ESLint job completed successfully |
| audit | FAIL | GHSA-r28c-9q8g-f849 via the old `postcss` pin; fixed on `develop` by #4500 |
| test | SKIPPED | Downstream job skipped after audit failure |
| ephemeral-integration | SKIPPED | Downstream job skipped after audit failure |
| merge-coverage | SKIPPED | Downstream job skipped after audit failure |
| docker-build | SKIPPED | GitHub check |
| license/cla | PASS | GitHub check |

## Findings

### Blocker
- `.github/workflows/ci.yml` / current PR head — GitHub's `audit` check fails on the old base dependency graph. Carry the change forward onto current `develop` (which includes #4500), then rerun checks so the PR head has usable green validation evidence.

## Breaking Changes
- [x] No public API, route, response, event, CLI, schema, or config contract is removed or renamed.
- [x] The added root script is additive.

## Test Coverage
Covered by `scripts/__tests__/lint-task-graph.test.mjs`; the lint GitHub check also exercised the new guard and actual ESLint invocation successfully.

**Comment by pkarw** [comment]
Label set to `changes-requested` because the current head has a failing required audit signal; autofix will carry it onto the updated base.

**Comment by pkarw** [comment]
Priority set to `priority-medium` because this restores an ordinary CI correctness regression.

**Comment by pkarw** [comment]
Risk set to `risk-low` because the change is isolated to CI tooling and tests with no runtime contract surface.

**Comment by pkarw** [comment]
Thanks @wojciechszyjka — review found the stale-base CI blocker, so I’m carrying the change forward onto current `develop` for the next pass.

**Comment by pkarw** [comment]
Closing in favor of #4501 (https://github.com/open-mercato/open-mercato/pull/4501).

Credit to @wojciechszyjka for the original implementation. The replacement PR carries the same work forward on current `develop`, plus the audit-unblocking patch, so it can merge without waiting on the fork branch.

**Comment by pkarw** [comment]
🤖 `om-auto-review-pr` completed: CHANGES REQUESTED on the superseded head; 1 autofix iteration produced merge-ready replacement #4501. Lock released.
