### ISSUE TITLE
bug: production build cannot load the pdfjs worker, so PDF text extraction and OCR return nothing

### ISSUE THREAD

**Issue by Kapsik89** [open-mercato/open-mercato#6398]
In a production build (`yarn build:app` + `yarn start`, Next 16.3.3, pdfjs-dist 6.2.108), text extraction and OCR fail for every uploaded PDF. The upload returns 200 and `attachments.content` stays `NULL`.

Reproduced on `develop` `8e520bbe0`. Not caused by #6264.

## Repro
1. `yarn build:packages && yarn generate && yarn build:app && yarn start`.
2. Upload any PDF that has a text layer.
3. `select content from attachments where id = …` → `NULL`. Same result with and without `OPENAI_API_KEY`.

## What the log says
- With a key (LLM OCR path): `Processing failed … Setting up fake worker failed: "Cannot find module '…/apps/mercato/.mercato/next/server/chunks/pdf.worker.mjs' imported from …/chunks/node_modules_pdfjs-dist_legacy_build_pdf_mjs_….js"`.
- Without a key (inline path): nothing. `extractPdfText` ends in a bare `catch { return null }` (`lib/textExtraction.ts:93`).

## Root cause, isolated on the same develop build
pdfjs-dist gets bundled into a server chunk. At runtime its fake worker imports `pdf.worker.mjs` from the chunks folder, and the build never puts that file there.

| build state | content of a 3-page text PDF |
|---|---|
| as built | `NULL` (both paths) |
| `pdf.worker.mjs` copied next to the chunk, server restarted | pages 1–3 |
| `'pdfjs-dist'` added to `serverExternalPackages` in `apps/mercato/next.config.ts`, rebuilt, no copy | pages 1–3; the chunk becomes a 405-byte `[externals]` shim; no "fake worker" error |

A restart is needed after any change, because pdfjs caches the failed worker setup.

## Why CI misses it
No integration test checks extracted PDF content. `TC-ATT-009` uploads `'%PDF-1.4 minimal document'` and only asserts HTTP 200.

## Not done
I didn't bisect for the introducing commit. pdfjs came in with `d120c34de` (#1250, 2026-04-12). The Next 16.x bumps (`5afd5982e`, `6aefc2f19` → 16.3.0, `70c37905e`) are the obvious suspects, but each bisect step needs a full `build:app`.

Severity: High (PDF content is empty in production builds). Found during QA of #6264.
