### PR TITLE
feat(ui): add RecordNotFoundState shared backend component

### PR DESCRIPTION
**Pull request by rajanbor**
Introduces RecordNotFoundState built on ErrorMessage for consistent page-level not-found handling. Adopted in customers/companies and customers/deals, separating the notFound state from generic load errors.

## Summary

Backend detail pages handled missing records inconsistently — some used custom centered markup, some collapsed not-found and load errors into one state. This PR introduces a shared `RecordNotFoundState` component and adopts it in the company and deal detail pages.

## Changes

- Added `RecordNotFoundState` component to `packages/ui/src/backend/detail`
- Exported it from the package barrel (`index.ts`)
- Adopted in `customers/companies/[id]/page.tsx` — separates `isNotFound` from generic `error`
- Adopted in `customers/deals/[id]/page.tsx` — adds `isNotFound` to `useDealData` hook

## Specification

**Does a spec exist for this feature/module?**
- [x] Yes
- [ ] No (created a new spec)
- [ ] N/A (minor change, no spec needed)

**Spec file path:**

`.ai/specs/2026-03-23-unified-record-not-found-ui-state.md`

## Testing

Verified manually against the running app:

- Existing company and deal detail pages load normally
- Missing record id shows `RecordNotFoundState` with a back button
- Generic load errors still render `ErrorMessage` without a back button

Integration tests were not added in this PR; they are planned as follow-up work together with the remaining detail pages.

## Checklist

- [x] This pull request targets `develop`.
- [x] I have read and accept the Open Mercato Contributor License Agreement (see `docs/cla.md`).
- [ ] I updated documentation, locales, or generators if the change requires it.
- [ ] I added or adjusted tests that cover the change.
- [ ] I added or updated integration tests in `.ai/qa/tests/` (or documented why integration coverage is not required).
- [ ] I created or updated the spec in `.ai/specs/` with a changelog entry (if applicable).

### Design System Compliance

- [x] No hardcoded status colors (`text-red-*`, `bg-green-*`, `text-emerald-*`, `bg-amber-*`, `bg-blue-*`) — use semantic tokens
- [x] No arbitrary text sizes (`text-[Npx]`) — use typography scale or `text-overline`
- [ ] Empty state handled for list/data pages (`<EmptyState>` or DataTable `emptyState` prop) — N/A
- [x] Loading state handled for async pages
- [ ] `aria-label` on all icon-only buttons (`<IconButton>`) — N/A
- [x] Uses existing DS components (Alert, StatusBadge, FormField) — no custom replacements

## Linked issues

### CODE REVIEW

**Comment by pkarw** [comment]
@zielivia please take a look from the UX point of view

**Review by pkarw — CHANGES_REQUESTED** [review]
Please fix the failing CI

**Comment by rajanbor** [comment]
**Follow-up fixes applied in second commit:**

  - `RecordNotFoundState` uses `useT()` for the default back-to-list label, no hardcoded strings
  - HTTP 404 from API now sets `isNotFound` in both `companies [id]/page.tsx` and `useDealData` hook (previously only a missing URL param triggered this state)
  - Added `ui.recordNotFound.backToList` to all app locale files (en/de/pl/es)
  - Completed deals i18n translations in de/pl/es; removed stale `backToList` and `notFound` keys from all four locale files

  **Spec scope:** 
  * Phase 1 complete (shared primitive).
  * Phase 2 partial complete. Companies and deals adopted.

**Comment by pkarw** [comment]
🤖 `auto-review-pr` started by @pkarw at 2026-05-24T11:20:30Z. Other auto-skills will skip this PR until the lock is released.

**Review by pkarw — CHANGES_REQUESTED** [review]
## Re-review: feat(ui): add RecordNotFoundState shared backend component

**Mode:** Re-review (head moved from `7d34b669` → `2c679b9d` since previous review).

### Summary
Solid work that aligns with the guidance in `packages/ui/AGENTS.md` ("For record-backed backend detail/edit pages, treat `notFound` as a dedicated page state, separate from generic `error`"). The new `RecordNotFoundState` primitive is a clean composition over `ErrorMessage` and the customers/companies + customers/deals pages have been wired correctly:

- `useDealData` now exposes `isNotFound` alongside `error` and the deal page renders the new primitive before the generic error branch.
- `companies/[id]/page.tsx` separates the 404 state from generic load errors with matching ordering.
- 404 detection on `apiCallOrThrow` is correct — `raiseCrudError` in `packages/ui/src/backend/utils/serverErrors.ts:285,291` attaches `status: res.status` to the thrown Error.
- Stale duplicate keys (`customers.deals.detail.backToList`, `customers.deals.detail.notFound`) are removed and not referenced anywhere else in the repo.
- de/pl/es translations for `customers.deals.detail.error.{load,notFound}` are filled in.
- Companies detail key `customers.companies.detail.actions.backToList` is preserved (still used by `companies-v2/[id]/page.tsx` and `CompanyHighlights.tsx`).

The only thing standing between this PR and merge is the same CI failure the prior review flagged — but now we know exactly why and how to fix it.

### Findings

#### Medium — CI `test` job blocked by unsorted i18n keys (Blocker)

The `test` GitHub Actions job is failing at the `yarn tsx scripts/i18n-check-sync.ts` step with:

```
[app] en.json: format issue (unsorted keys)
[app] pl.json: format issue (unsorted keys)
[app] es.json: format issue (unsorted keys)
[app] de.json: format issue (unsorted keys)
[customers] en.json: format issue (unsorted keys)
[customers] es.json: format issue (unsorted keys)
6 issues found across 2 modules
```

Root causes per file (`scripts/i18n-check-sync.ts` requires all flat keys to be alphabetically sorted):

1. **`apps/mercato/src/i18n/{en,pl,es,de}.json`** — `ui.recordNotFound.backToList` was inserted between `ui.forms.flash.saveSuccess` and `ui.forms.listbox.noMatches`. Alphabetically `ui.recordNotFound.*` sorts **after** every `ui.forms.*` key, so it must be moved below the entire `ui.forms.*` block (and likely fall between `ui.notifications.*` and `ui.settings.*` once sorted — `yarn i18n:check-sync --fix` will place it correctly).
2. **`packages/core/src/modules/customers/i18n/{en,es}.json`** — `customers.deals.detail.actions.backToList` (and in `es.json` also `customers.companies.detail.actions.backToList`) was moved from its sorted position into a non-sorted spot inside the `customers.deals.detail.actions.*` group. The key belongs alphabetically before `cancel`, where it already was on `develop`.

**Fix** — run from repo root and commit the result:

```bash
yarn i18n:check-sync --fix
```

This will rewrite the six affected files in deterministic sorted order without changing any values. After the commit, the `test` job should pass.

#### Low — Optional: smoke test for `RecordNotFoundState`

The component is a small presentational composition over already-tested primitives (`ErrorMessage`, `Button`, `Link`), so the absence of a test is borderline. The directory already contains `packages/ui/src/backend/detail/__tests__/InlineEditors.test.tsx` as a convention. A tiny render test asserting that:

- the `label` and (when provided) `description` reach the `ErrorMessage`,
- the default back action renders only when `backHref` is set,
- a custom `action` overrides the default,

…would lock the contract for downstream modules. **Not a blocker** given the composition is trivial, but worth ~10 lines if you're already touching the file.

### Things that look right (no action needed)

- `RecordNotFoundState.tsx` uses `useT()`, `cn()`, semantic spacing (`py-16 px-4`, no arbitrary values), no `dark:` overrides on tokens, no raw `<button>` / `<input>`, no hardcoded colors.
- `RecordNotFoundStateProps` is exported alongside the component from `packages/ui/src/backend/detail/index.ts` so external modules can type their wrappers.
- The new branch in both detail pages is placed *before* the generic error branch — required so the more specific state wins.
- de/pl/es translations filled in for previously-English-only `customers.deals.detail.error.{load,notFound}` — nice cleanup beyond the original spec.
- No `any` types added, no `em.find`/`em.findOne` introduced, no raw `fetch(`, no contract-surface changes (events / widget IDs / API routes / DB schema / DI keys / ACL features / notification IDs all untouched), no missing `organization_id` / `tenant_id` filters.

### Verdict

**Changes requested** — single mechanical fix (`yarn i18n:check-sync --fix` + commit) unblocks the `test` CI job. Once green, this is good to land.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by pkarw** [comment]
Label set to `changes-requested` because review found actionable issues (CI `test` job blocked by 6 unsorted i18n locale files; details in the review above).

**Comment by pkarw** [comment]
Thanks @izqzmyli — re-review found one remaining actionable item (sorting 6 locale files via `yarn i18n:check-sync --fix`), so I'm handing this PR back to you for the next pass. When the updated commit is pushed, re-request review and the automation can pick it up from the latest head.

**Comment by pkarw** [comment]
🤖 `auto-review-pr` completed: CHANGES REQUESTED. Single mechanical blocker (unsorted i18n keys in 6 files). Lock released; handed back to author. No autofix iterations attempted (fork PR with actively-iterating author; one-command fix is more efficient than carry-forward replacement).

**Comment by pkarw** [comment]
🤖 `auto-review-pr` re-review started by @pkarw at 2026-05-26T05:25:42Z. Other auto-skills will skip this PR until the lock is released.

**Review by pkarw — APPROVED** [review]
## Re-review: feat(ui): add RecordNotFoundState shared backend component

**Mode:** Re-review (head moved from `2c679b9d` → `784755d8` since previous review).

### Summary

Previous review identified one mechanical blocker — the `test` CI job failed `yarn i18n:check-sync` because `ui.recordNotFound.backToList` and the moved `customers.deals.detail.actions.backToList` keys were inserted out of alphabetical order in 6 locale files. Commit `784755d8` ("fix(i18n): sort locale keys to pass i18n-check-sync") sorts those 6 files. Nothing else changed since `2c679b9d`.

### Verification of the resolved blocker

- `yarn i18n:check-sync` locally: **`All translation files are in sync.`** ✓
- All 8 affected locale files (`apps/mercato/src/i18n/{en,pl,es,de}.json` + `packages/core/src/modules/customers/i18n/{en,pl,es,de}.json`) have keys in deterministic alphabetical order.
- CI `test` job on this head: **SUCCESS** (run 26360373782/job 77811854515).

### Re-checks against previous review

| Area | Status |
|------|--------|
| `RecordNotFoundState` component contract matches `.ai/specs/2026-03-23-unified-record-not-found-ui-state.md` §Proposed component contract | ✓ |
| `useDealData` exposes `isNotFound` and the deal page renders the new primitive before the generic error branch | ✓ |
| `companies/[id]/page.tsx` separates 404 state from generic load errors with matching ordering | ✓ |
| 404 detection on `apiCallOrThrow` (status attached by `raiseCrudError`) | ✓ |
| Stale duplicate keys removed and not referenced anywhere else | ✓ (grep clean for `customers.deals.detail.notFound` and `customers.deals.detail.backToList`) |
| de/pl/es translations filled in for `customers.deals.detail.error.{load,notFound}` and `customers.deals.detail.actions.backToList` | ✓ |
| Boy-Scout cleanup: `flex h-[50vh]` arbitrary value removed from companies error branch | ✓ |
| No raw `fetch(`, no `em.find`, no `any`, no `alert(`, no DS violations, no contract-surface changes | ✓ |
| All keys preserved that are still referenced (`customers.companies.detail.actions.backToList` is kept; consumed by `companies-v2/[id]/page.tsx` and `CompanyHighlights.tsx`) | ✓ |

### Validation gate (in isolated review worktree)

- `yarn install` (mode=skip-build) — clean
- `yarn build:packages` — 19/19 successful
- `yarn generate` — 354 OpenAPI paths, all generators completed
- `yarn workspace @open-mercato/ui run typecheck` — clean
- `yarn workspace @open-mercato/core run typecheck` — only the pre-existing `tsconfig.json(7,27): error TS5103: Invalid value for '--ignoreDeprecations'` regression on develop (introduced by PR #2067 dependabot TS 6.0 bump, identical bytes on `origin/develop` and this PR; not caused by this PR — needs a separate develop-branch fix)
- `yarn workspace @open-mercato/ui run test --testPathPatterns="detail"` — 15/15 passed (1 suite)
- `yarn workspace @open-mercato/core run test --testPathPatterns="customers/.*deals|customers/.*companies"` — 95/95 passed (16 suites)
- `yarn i18n:check-sync` — `All translation files are in sync.`

### CI on PR head

- `test`, `lint`, `prepare`, `audit`, `license/cla` — SUCCESS
- `ephemeral-integration (1/15, 9/15)` — SUCCESS; remaining shards IN_PROGRESS/QUEUED (running, not failing)
- `docker-build`, `Standalone App Integration Tests`, `Publish Snapshot` — SKIPPED (fork PR, expected)

### Findings

**0 Critical / 0 High / 0 Medium / 0 Low.**

The previous Low ("optional smoke test for `RecordNotFoundState`") was explicitly non-blocking in the prior review and remains so — the component is a thin presentational composition over already-tested `ErrorMessage` + `Button` + `Link`. Not re-raising.

### Verdict

**Approved.** Setting pipeline label to `qa` because this is a customer-facing UI change to two CRM detail pages (companies + deals) that warrants a quick manual exercise of the 404 path; adding `feature` category label. Label `needs-qa` applied so manual QA picks it up.

#### Suggested QA steps

1. Open `/backend/customers/companies/<invalid-uuid>` — expect `RecordNotFoundState` with `"Company not found."` message and **Back to companies** button that navigates to `/backend/customers/companies`.
2. Open `/backend/customers/deals/<invalid-uuid>` — expect `RecordNotFoundState` with `"Deal not found."` message and **Back to deals** button that navigates to `/backend/customers/deals`.
3. Confirm a valid record still loads normally on both pages.
4. Spot-check the de/pl/es translations on each page by switching locale.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by pkarw** [comment]
Label set to `qa` because the i18n-sort blocker is resolved (0/0/0/0 findings) and this is a customer-facing UI change to two CRM detail pages (companies + deals) that warrants a quick manual exercise of the 404 path.

**Comment by pkarw** [comment]
🤖 `auto-review-pr` completed: APPROVED. The single mechanical blocker from the previous review (unsorted i18n keys) is fixed by `784755d8`. 0/0/0/0 findings on the re-review. Labels: `qa` + `needs-qa` + `feature`. Lock released.

**Comment by zielivia** [comment]
@pkarw  @izqzmyli 
LGTM as an interim step — the notFound/error split itself is the right call and matches packages/ui/AGENTS.md:343-345. Flagging a few things so we don't lock this in as the canonical pattern:

1. Treat as temporary until a proper not-found primitive exists. RecordNotFoundState currently wraps ErrorMessage, which is destructive-styled (border-destructive/50 bg-destructive/5 text-destructive). On a full-page "record not found" surface that reads as "something is broken" rather than "this page doesn't exist." A dedicated primitive — neutral background, non-destructive icon (FileQuestion / SearchX), larger layout — would be the DS-aligned solution. Happy to file a follow-up issue.

2. Vertical layout regressed. Old code used h-[50vh] + justify-center so the empty state sat in the visual center of the viewport. New wrapper has py-16 with no height — justify-center becomes a no-op and the alert sits near the top of PageBody. Worth at least min-h-[50vh] until the new primitive lands.

3. Real regression on the generic error branch. In both companies/[id]/page.tsx and deals/[id]/page.tsx, the old code's error || notFound branch had a Back to <list> button. The new bare <ErrorMessage label={...} /> has no action — users hitting a 5xx / network error now have no recovery path. Please restore the back-to-list action on this branch before merge.

4. PL terminology drift in customers/deals. The module uses "szansa" consistently (entityPlural: "szanse", loadError: "Nie udało się wczytać szansy.", edit.notFound: "Nie znaleziono szansy.", 25+ keys). The 3 strings touched by this PR use "transakcja" instead:

customers.deals.detail.actions.backToList: "Powrót do listy transakcji"
customers.deals.detail.error.load: "Nie udało się załadować transakcji."
customers.deals.detail.error.notFound: "Nie znaleziono transakcji."
Please align with "szansa" — there's already customers.deals.edit.notFound: "Nie znaleziono szansy." to mirror.

Summary: #3 and #4 are merge-blockers IMO (regression + terminology). #1 and #2 are interim-acceptable if we agree to file a follow-up for a proper DS-compliant NotFoundState primitive.

**Comment by rajanbor** [comment]
@zielivia thanks a lot for the detailed review.

1) Not sure if this is something I should decide on my own (it's a design system call - neutral vs destructive styling for not-found states), so leaving it untouched for now.

2) Fixed: changed `py-16` to `min-h-[50vh]` so `justify-center` actually has space to center the content properly again.

3) Fixed: restored the back-to-list `Button + Link` action for the generic error state in both `companies/[id]` and `deals/[id]`. Sorry about that regression - it got accidentally removed while splitting out the `isNotFound` state.

3) Fixed: updated the three PL translations to consistently use “szansa”, matching the wording used across the rest of the module.

**Comment by pkarw** [comment]
Thanks! Will do another round of review and merge it in @zielivia would you please take care of the DS wide call (1st issue listed)?

**Comment by pkarw** [comment]
🤖 `auto-review-pr` started by @pkarw at 2026-05-27T03:47:54Z. Other auto-skills will skip this PR until the lock is released.

**Review by pkarw — APPROVED** [review]
## Re-review: feat(ui): add RecordNotFoundState shared backend component

**Mode:** Re-review (head moved from `784755d8` → `4001011f` since previous APPROVED review).

### Summary

One follow-up commit (`4001011f`, "fix: restore back button on error branch, fix PL locale and RecordNotFoundState layout") with a 4-file / +18/-4 delta:

| File | Change | Verdict |
|------|--------|---------|
| `packages/ui/src/backend/detail/RecordNotFoundState.tsx` | swap `py-16` → `min-h-[50vh]` for vertical centering | Consistent with existing convention (see Findings) |
| `packages/core/src/modules/customers/backend/customers/companies/[id]/page.tsx` | add `action` back-to-list button to the generic `error` branch's `ErrorMessage` | Correct UX improvement — recovery path on transport/parse failures, doesn't touch the (already approved) `RecordNotFoundState` 404 branch |
| `packages/core/src/modules/customers/backend/customers/deals/[id]/page.tsx` | same as above — `action` back-to-list button on the generic `error` branch | Same — correct |
| `packages/core/src/modules/customers/i18n/pl.json` | `transakcji`/`transakcji` → `szans`/`szansy` for `customers.deals.detail.{error.load,error.notFound,actions.backToList}` | Aligns with the rest of the module's PL terminology (`szansa`, `szansy`, `szansę`, `Utwórz szansę`) |

The branch ordering on both pages still matches the spec's contract — `isNotFound` (renders `RecordNotFoundState`) is checked before the generic `error` branch (renders `ErrorMessage`), so the more specific state wins.

### Re-checks against previous review

| Area | Status |
|------|--------|
| `RecordNotFoundState` component contract matches `.ai/specs/2026-03-23-unified-record-not-found-ui-state.md` §Proposed component contract | ✓ (props unchanged) |
| `useDealData` exposes `isNotFound` and the deal page renders the new primitive before the generic error branch | ✓ |
| `companies/[id]/page.tsx` separates 404 state from generic load errors with matching ordering | ✓ |
| 404 detection on `apiCallOrThrow` (status attached by `raiseCrudError`) | ✓ |
| Stale duplicate keys removed and not referenced anywhere else | ✓ |
| de/pl/es translations filled in for `customers.deals.detail.error.{load,notFound}` and `customers.deals.detail.actions.backToList` | ✓ |
| No raw `fetch(`, no `em.find`, no `any`, no `alert(`, no DS violations beyond the layout-token note below, no contract-surface changes | ✓ |
| `customers.companies.detail.actions.backToList` and `customers.deals.detail.actions.backToList` translation keys exist in all 4 locales and are reused (not new keys) | ✓ |
| i18n keys remain alphabetically sorted (`yarn i18n:check-sync`) | ✓ — `All translation files are in sync.` |

### Diff-level automated checks (step 5)

| Pattern | Result |
|---------|--------|
| Removed/renamed event ID, widget spot ID, API response field, DB column, public import path | None — no contract surface touched |
| Tenant-scope filter removed | N/A — UI-only change |
| `findWithDecryption`/`findOneWithDecryption` downgraded | N/A — no data access changes |
| New API route missing `openApi` / `metadata` | N/A — no API routes added |
| Raw `fetch(` / new `em.find(...)` in UI or backend | None |
| Behavior change without tests | Layout/recovery-action change only; the prior review's "optional smoke test for `RecordNotFoundState`" remained explicitly non-blocking and that posture is unchanged here (composition over already-tested `ErrorMessage` + `Button` + `Link`) |
| Hardcoded user-facing strings / new `any` / `alert(` | None |
| Manual migration SQL / entity schema change without migration | N/A — no DB changes |
| Unsorted i18n keys | None — verified locally |

### Validation gate (in isolated review worktree)

- `yarn install` (mode=skip-build) — clean
- `yarn build:packages` — 19/19 successful
- `yarn generate` — 354 OpenAPI paths, all generators completed
- `yarn workspace @open-mercato/ui run typecheck` — **clean**
- `yarn workspace @open-mercato/core run typecheck` — only the pre-existing `tsconfig.json(7,27): error TS5103: Invalid value for '--ignoreDeprecations'` from PR #2067 (dependabot TS 6.0 bump on `develop`, commit `1427e5814`); identical bytes on `origin/develop` and this PR; **not caused by this PR**
- `yarn i18n:check-sync` — **`All translation files are in sync.`**

Local unit tests (`yarn workspace @open-mercato/{ui,core} run test --testPathPatterns=…`) reproduce a `React.act is not a function` failure on a set of test files that are **not** touched by this PR (`DealsSection.test.tsx`, `resolveSafeInlineUrlHref`, etc.); this is a React / `@testing-library/react` version skew on `develop` (tied to the same dependabot bump cluster) and is **not** introduced here. CI confirms this: the `test` job on PR head `4001011f` is **SUCCESS** (run `26451582208`/job `78004136787`), matching the prior approved review's CI result on `784755d8`.

### CI on PR head (`4001011f`)

- `test`, `lint`, `prepare`, `audit`, `license/cla` — **SUCCESS**
- `ephemeral-integration (1..15/15)` — IN_PROGRESS / QUEUED (no failures)
- `docker-build`, `Standalone App Integration Tests`, `Publish Snapshot` — SKIPPED (fork PR, expected)

### Findings

**0 Critical / 0 High / 0 Medium / 0 Low.**

Note (informational, not a finding): `RecordNotFoundState.tsx` swaps the prior `py-16` (DS scale spacing) for `min-h-[50vh] px-4`. Strict reading of `.ai/ds-rules.md` flags arbitrary values, but the rule's stated examples (`text-[13px]`, `p-[13px]`, `rounded-[24px]`, `z-[9999]`) are pixel/scalar values; viewport-fraction sizing for centered empty/loading states is an established cross-repo convention — `packages/ui/src/primitives/dialog.tsx:66` uses `min-h-[50vh] max-h-[70vh]`, and dozens of detail-page empty/loading states (across `business_rules`, `customer_accounts`, `workflows`, `sales`, `customers/deals/pipeline`, `customers/companies`, `customers/people`, `workflows/visual-editor`, etc.) use `h-[50vh]` / `min-h-[50vh]`. Unifying that into the shared primitive is consistent with the spec's intent to standardize this state. If the team wants to formalize it, that would be a follow-up DS-scale token (e.g., `min-h-empty-state`) and a sweep — out of scope for this PR.

### Verdict

**Approved.** Pipeline label stays `qa` (kept from prior review — the PR has `needs-qa` and no `skip-qa`, so manual QA is still the gate). `feature` category label preserved.

#### Suggested QA steps (unchanged from prior review)

1. Open `/backend/customers/companies/<invalid-uuid>` — expect `RecordNotFoundState` with `"Company not found."` message and **Back to companies** button that navigates to `/backend/customers/companies`.
2. Open `/backend/customers/deals/<invalid-uuid>` — expect `RecordNotFoundState` with `"Deal not found."` message and **Back to deals** button that navigates to `/backend/customers/deals`.
3. Force a generic load error on either page (e.g., temporarily break the API URL) — expect `ErrorMessage` with the same **Back to {companies,deals}** recovery action newly added in this commit.
4. Confirm a valid record still loads normally on both pages.
5. Spot-check the de/pl/es translations on each page by switching locale; verify the PL terminology now uses "szansa/szansy/szans" consistently (no leftover "transakcja/transakcji").

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by pkarw** [comment]
Label kept as `qa` because re-review on commit `4001011f` passed (0 findings) and `needs-qa` is still present for manual exercise.

**Comment by pkarw** [comment]
🤖 `auto-review-pr` completed: APPROVED. Re-review of commit `4001011f` (head moved from `784755d8`): 0 findings, no autofix needed. Pipeline label remains `qa`. In-progress lock released.

**Comment by zielivia** [comment]
> Thanks! Will do another round of review and merge it in @zielivia would you please take care of the DS wide call (1st issue listed)?

Ofc.
