### PR TITLE
fix(core): make multi-table writes atomic in perspectives/messages/inbox_ops (#2340)

### LINKED ISSUE #2340: Dashboards/perspectives/messages/inbox_ops: atomic multi-table writes
Part of #2333.

**HIGH**
- `perspectives/api/[tableId]/route.ts` POST — 3 independent committing writes (saveUserPerspective / saveRolePerspectives / clearRolePerspectives); wrap in one txn.
- `perspectives/services/perspectiveService.ts` `saveRolePerspectives` (per-role nativeUpdate de-default + single trailing flush, loop-write).
- `messages/commands/messages.ts` `updateDraftCommand` — delete+recreate across 3 tables + `linkAttachmentsToMessage` find before flush (UoW-loss); mirror `composeMessageCommand`'s `em.transactional`.
- `inbox_ops/api/emails/[id]/reprocess/route.ts` + `retireActiveProposalsForEmail` — proposal/action scalar mutate then discrepancy find before flush (UoW-loss) + 2 commits.

**MEDIUM**
- `messages/commands/shared.ts` `restoreMessageAggregateSnapshot`; `perspectiveService.saveUserPerspective`; `attachments/api/route.ts` + `library/[id]/route.ts` POST/PATCH/DELETE (entity + custom-fields/storage split). **LOW:** `dashboards/api/users/widgets/route.ts` redundant flush.

### PR DESCRIPTION
**Pull request by adeptofvoltron**
Fixes #2340

## Problem
Several multi-table write paths in `dashboards`/`perspectives`/`messages`/`inbox_ops` issued independent `em.flush()` / `nativeDelete` / `nativeUpdate` commits without an enclosing transaction. A mid-path failure left earlier writes committed (PARTIAL-COMMIT), and some paths ran `em.find` between a scalar mutation and `flush` (UoW-LOSS). Part of the SQL transaction-safety audit umbrella #2333; depends only on `withAtomicFlush` which already exists on `develop`.

## Root Cause
Neither `makeCrudRoute` nor `CommandBus` wraps a write in a DB transaction, so atomicity depends on each command/route calling `withAtomicFlush({ transaction: true })` (or `em.transactional`) — and these paths did not. `composeMessageCommand` already does it correctly; the siblings here were the gap.

## What Changed
- **perspectives `POST /api/perspectives/[tableId]`** (HIGH): role-op RBAC + role-existence validation now runs **before** any write; `saveUserPerspective` + `saveRolePerspectives` + `clearRolePerspectives` run inside one `withAtomicFlush({ transaction: true })`. (Behavior note: a `403`/`400` on role ops no longer leaves the personal perspective committed — the request is now all-or-nothing.)
- **messages `updateDraftCommand`** (HIGH): the delete+recreate of recipients/objects/attachments + `linkAttachmentsToMessage` + the send-transition validation/mutation are wrapped in one transaction. Previously the `nativeDelete` of recipients committed immediately, so a later "at least one recipient is required" / "subject is required" throw left the draft with its recipients already deleted.
- **inbox_ops `POST .../emails/[id]/reprocess`** (HIGH): `retireActiveProposalsForEmail` (proposal/action/discrepancy mutations) + the email requeue (`status='received'`) now commit atomically; removed the now-redundant inner `em.flush()`.
- **messages `restoreMessageAggregateSnapshot`** (MEDIUM, undo path): the full message/recipient/object reconcile + attachment relink (with interleaved `em.find`s) is wrapped in one transaction.
- **dashboards `PUT /api/dashboards/users/widgets`** (LOW): dropped the redundant double `flush()` on the `inherit` branch.

### Deferred (documented)
- **attachments `POST` / `library/[id] PATCH`** (MEDIUM, entity + custom-fields split): custom fields are written through `dataEngine.setCustomFields` on a **separate** persistence path, not the request `em`, so a naive `withAtomicFlush(em, …)` wrap cannot make the two atomic and risks two-connection contention. This is the same entity+custom-fields concern as the framework-level CRITICAL finding (#2335) and should be solved there generically rather than hand-rolled per route.

## Tests
- `messages.update-draft.test.ts`: added begin/commit/rollback ordering assertions on the send path + a new "rolls back and emits no events when the atomic flush fails" case.
- `inbox_ops .../reprocess/route.test.ts`: added begin/commit assertions on success + a rollback-on-flush-failure case (verifies no events emitted, returns 500). Updated EM mocks with `begin`/`commit`/`rollback`.
- Validation: `yarn build:packages` ✅, `yarn generate` ✅, `yarn typecheck` ✅ (19/19), `yarn workspace @open-mercato/core test` ✅ (4497 passed; the single `customers/ChangelogFilters` failure is a pre-existing parallel-run flake that passes in isolation and is untouched by this PR). `yarn lint` could not run — the worktree's `eslint-plugin-react`/`eslint` versions are incompatible (`resolveBasedir … getFilename is not a function`), crashing on `apps/mercato/next.config.ts` before reaching any changed file; environmental, not introduced here.

## Backward Compatibility
No contract-surface changes (no API shape, event ID, DI, ACL, or signature changes). Each fix changes only *when* a write commits (atomically), never *what* commits; side effects/events still fire only after commit. The non-transactional `withAtomicFlush` path is unchanged.

## Security impact
inbox_ops reprocess and perspectives role-defaults are authorization-relevant write paths. Making them atomic removes partial-state windows (e.g. proposals retired but email not requeued; personal perspective saved despite a `403` on role defaults). No change to the RBAC checks themselves; feature guards (`inbox_ops.proposals.manage`, `perspectives.role_defaults`) are unchanged.

### CODE REVIEW

**Comment by adeptofvoltron** [comment]
auto-fix-github did not added here integration tests. So I am doing them right now.

**Comment by adeptofvoltron** [comment]
auto-fix-github did not added here integration tests. So I am doing them right now.

**Comment by adeptofvoltron** [comment]
## Follow-up pushed: UoW-loss ordering + atomicity integration test

Addressing the two gaps identified when re-checking this PR against the umbrella (#2333), whose audit classified `inbox_ops reprocess` as **UoW-loss + commits** (both dimensions) and whose validation strategy asks for ephemeral-Postgres atomicity tests.

**Why the extra change was needed:** `develop`'s `withAtomicFlush` uses a *single trailing flush* (the per-phase-flush boundary is a known, intentionally-deferred gap from #2343). So wrapping `{ transaction: true }` closes the **partial-commit** dimension, but does **not** by itself close **UoW-loss** — a query between a scalar mutation and the flush can still reset the Unit of Work (SPEC-018 Problem 1). The fix is explicit read-before-write ordering.

- `inbox_ops` `retireActiveProposalsForEmail`: moved the `InboxDiscrepancy` find **above** the proposal/action mutations — all reads now precede all writes.
- `messages` `restoreMessageAggregateSnapshot`: resolve all ORM finds (message, recipients, objects, attachments-to-relink) up front, then apply mutations + `nativeDelete`.
- `perspectives`: added `TC-PERSP-ATOMIC-001` integration test — POST with an invalid role → 400 with **no** partial personal perspective persisted (distinguishes the fixed behavior from the pre-fix partial commit), plus a no-role happy path with cleanup.

**Validation:** `yarn build:packages` ✅, `yarn typecheck` ✅ (19/19), affected unit suites ✅ (8 tests incl. rollback-on-failure). The new integration spec typechecks and conforms to the `__integration__` harness contract, but I could not get a green **local** `yarn test:integration:ephemeral` run: the ephemeral app server crashed at the readiness check due to port/DB contention from concurrent ephemeral worktrees on this machine (4 parallel runs). It was **not** a test-logic or app-code failure — bootstrap (`initialize` + 170s build) succeeded; the dev server exited before serving. CI runs each PR in isolation and will execute the spec cleanly.

**Comment by pkarw** [comment]
🤖 `auto-review-pr` started by @pkarw at 2026-06-01T20:50:00Z. Other auto-skills will skip this PR until the lock is released.

**Review by pkarw — APPROVED** [review]
## Code Review: fix(core): make multi-table writes atomic in perspectives/messages/inbox_ops (#2340)

**Verdict: ✅ Approved**

This PR closes the partial-commit / Unit-of-Work-reset class of bug (SPEC-018 Problem 1) by routing multi-table writes through the established `withAtomicFlush(em, phases, { transaction: true })` helper, hoisting all reads ahead of mutations, and keeping side-effect emissions outside the transaction.

### What I verified
- **Tests (full `@open-mercato/core` suite):** `547 passed, 547 total` · `4505 passed, 4505 total` (run with `NODE_ENV=test` after `yarn build:packages && yarn generate`).
- **Typecheck (`tsc --noEmit` in `packages/core`):** clean, exit 0.
- **Root cause of the red `test` CI check:** the PR branch was based on a stale `develop`. Merging the latest `develop` (which includes the timer-validator datetime test fix, #2391) resolves it. The merge was conflict-free and has been pushed to the PR branch.

### Strengths
- Correct use of `withAtomicFlush` with `{ transaction: true }` for all-or-nothing semantics; side effects (`emit*Event`, query-index upserts) stay **after** commit.
- Reads are hoisted before mutations in `inbox_ops` reprocess and `messages` snapshot restore, with a clear comment explaining the UoW-reset hazard.
- Removed a redundant double `em.flush()` in `dashboards/api/users/widgets/route.ts`.
- **Excellent test coverage** of the atomicity contract: the new unit tests assert `begin`/`commit`/`rollback` call ordering, rollback-on-failure with **no** events emitted, and flush-before-side-effects ordering. `TC-PERSP-ATOMIC-001` adds an integration-level atomicity spec.
- Internal error messages use the `[internal]` prefix per the i18n convention.

### Diff-level automated checks
- No frozen-contract removals (events, spot IDs, response fields, DB columns, import paths).
- No tenant-isolation regressions; `findWithDecryption`/`findOneWithDecryption` retained (no downgrade to raw `em.find`).
- The raw `em.find`/`em.findOne` calls in `messages/commands/shared.ts` are **pre-existing** (relocated, not introduced).
- Behavior changes ship with tests. ✔

### Non-blocking notes
- The pre-existing user-facing validation messages in `updateDraft` (`'at least one recipient is required'`, `'subject is required'`, `'body is required'`) are plain `throw new Error(...)` strings. They were only relocated into the atomic closure by this PR, not introduced, so routing them through `t('messages.errors.*')` is out of scope here — worth a follow-up.

### QA
Marking `needs-qa`: these are customer-facing write paths (compose/send message, inbox email reprocess, save table perspective). Unit tests mock the EntityManager, and only perspectives has a real-DB atomicity integration test, so a quick manual pass over message-send and inbox-reprocess against a live DB is warranted before merge.

**Comment by pkarw** [comment]
Label set to `qa` because code review passed and these customer-facing write paths (message send, inbox reprocess, perspective save) still need a manual QA pass. Also merged the latest `develop` into the branch, which clears the previously-failing `test` check (stale base).

**Comment by pkarw** [comment]
🤖 `auto-review-pr` completed: APPROVED. Merged latest `develop` in (conflict-free, pushed), verified core tests (4505 passing) + typecheck locally. Routed to `qa`. Lock released.

**Comment by pkarw** [comment]
🧪 Added `TC-PERSP-ATOMIC-VERIFY.spec.ts` — verifies perspective settings (incl. v2 filter tree) round-trip and atomic role-perspective save. **Green** on a live ephemeral instance. (messages `updateDraft` and inbox_ops `reprocess` are HTTP-reachable but require heavy ingestion/AI-pipeline setup; they remain covered by their unit suites.) Table: https://github.com/open-mercato/open-mercato/issues/2333#issuecomment-4599797031
